name: 'Package'
on: [workflow_dispatch]
jobs:
  tests:  
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        php: [53, 54, 55]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_11.7.app
      - name: Install macports
        run: |
          curl -o /tmp/macports.pkg -sL https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-10.15-Catalina.pkg
          sudo installer -pkg /tmp/macports.pkg -target /
          echo "/opt/local/bin" | sudo tee -a $GITHUB_PATH
      - name: Update and sync macports
        run: |
          sudo port -vN selfupdate
          sudo port -vN sync
      - name: Package
        run: sudo port -N mpkg php${{ matrix.php }} php${{ matrix.php }}-cgi php${{ matrix.php }}-fpm php${{ matrix.php }}-imagick
      - name: Copy to builds
        run: |
          sudo mkdir /tmp/builds
          sudo find /opt/local/var -type f -name "*.pkg" -exec cp -n {} /tmp/builds \;
          sudo find /opt/local/var -type f -name "*.mpkg" -exec cp -n {} /tmp/builds \;
      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: /tmp/builds