name: Test
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['53', '54', '55']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        run: bash install.sh ${{ matrix.php-versions }}
      - name: Testing PHP version
        run: |
          php -v
          php -r "if(strpos(phpversion(), '${{ matrix.php-versions }}') === false) {throw new Exception('Wrong PHP version Installed');}"
      - name: Testing
        run: |
          php -m